Update server go.doc
google/go-tika pull request #35
Opened 2022-03-31 12:07 UTC by nathj07

When working with this it was not immediately clear that the `version` parameter was not simply a string.

I figured it out reading the code, and hopefully this little update will be useful to others too.

2022-04-01 13:07 UTC, tbpg requested changes
Thank you! Just a couple minor whitespace changes and I'd be happy to merge this.

2022-04-01 13:07 UTC, tbpg commented on .gitignore
> +*.idea
```suggestion
*.idea

```

2022-04-01 13:07 UTC, tbpg commented on tika/doc.go
> +current working directory.
```suggestion
for removing the file when no longer needed.

Version is a custom type,
and should be passed as such. There are constants in the code for these.
The following example downloads version 1.21 to the named JAR in the
current working directory.
```

(New paragraph, need to adjust line breaks.)

2022-04-01 13:54 UTC, tbpg approved these changes

2022-04-01 14:00 UTC, nathj07 commented
the lint failure is unclear to me, is there something I need to change?

2022-04-18 03:10 UTC, tbpg commented
@nathj07, would you mind pulling in the latest changes from main? Looks like I don't have edit access. I updated the CI config and it seems to be working now.

2022-04-18 16:00 UTC, merged